name: Build ESXI Image

on:
  push:
    branches:
       - 'main'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout Branch
        uses: actions/checkout@main
        with:
          ref: main

      - name: Install python packge
        run: python -m pip install -U pip six lxml psutil pyOpenSSL

      - name: Initialization Environment
        run: |
          choco install vmware-powercli-psmodule
      #     choco install python310 --params "/InstallDir:.\python"
      #     C:\ProgramData\chocolatey\bin\python3.10.exe -m pip install -U pip six lxml psutil pyOpenSSL
          # Set-PowerCLIConfiguration -PythonPath C:\ProgramData\chocolatey\bin\python3.10.exe -sip ESXi-6.7.0-20220604001-standard -load net-igb,net55-r8168

      - name: Build image
        run: |
          .\ESXi-Customizer-PS.ps1 -v65 -load net-igb,net55-r8168
          cat C:\Users\RUNNER~1\AppData\Local\Temp\*.log
          dir

      - name: Upload firmware
        uses: actions/upload-artifact@main
        with:
          name: ESXi-6.7.iso
          path: .\*.iso
